apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kanarystatefulsets.kanary.k8s-operators.dev
spec:
  group: kanary.k8s-operators.dev
  names:
    kind: KanaryStatefulset
    listKind: KanaryStatefulsetList
    plural: kanarystatefulsets
    singular: kanarystatefulset
    shortNames:
    - ks
    - kanary
  additionalPrinterColumns:
  - name: Status
    type: string
    description: Status for the KanaryStatefulset.
    JSONPath: ".status.report.status"
  - name: StatefulSet
    type: string
    description: StatefulSet Name used for the KanaryStatefulset.
    JSONPath: ".spec.statefulSetName"
  - name: Service
    type: string
    description: Service Name used for the KanaryStatefulset.
    JSONPath: ".spec.serviceName"
  - name: Traffic
    type: string
    description: Traffic type used for the KanaryStatefulset.
    JSONPath: ".spec.traffic.source"
  - name: Scale
    type: string
    description: Scale type used for the KanaryStatefulset.
    JSONPath: ".status.report.scale"
  - name: Validation
    type: string
    description: Validation configuration used for the KanaryStatefulset.
    JSONPath: ".status.report.validation"
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
