apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanary
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kanary
  template:
    metadata:
      labels:
        name: kanary
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: kanary
      containers:
        - name: kanary
          image: registry.cn-hangzhou.aliyuncs.com/k8s-kanary/kanary:v1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - kanary
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kanary"
