apiVersion: kanary.k8s-operators.dev/v1alpha1
kind: KanaryDeployment
metadata:
  name: nginx-dep
  labels:
    app: nginx
spec:
  serviceName: nginx
  deploymentName: nginx-dep
  scale:
    static:
      replicas: 1
  traffic:
    source: both
  validation:
    items:
    - manual:
        statusAfterDeadline: none
  template:
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:latest
            ports:
            - containerPort: 80