// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousValueDeviation) DeepCopyInto(out *ContinuousValueDeviation) {
	*out = *in
	if in.MaxDeviationPercent != nil {
		in, out := &in.MaxDeviationPercent, &out.MaxDeviationPercent
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousValueDeviation.
func (in *ContinuousValueDeviation) DeepCopy() *ContinuousValueDeviation {
	if in == nil {
		return nil
	}
	out := new(ContinuousValueDeviation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscreteValueOutOfList) DeepCopyInto(out *DiscreteValueOutOfList) {
	*out = *in
	if in.GoodValues != nil {
		in, out := &in.GoodValues, &out.GoodValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BadValues != nil {
		in, out := &in.BadValues, &out.BadValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TolerancePercent != nil {
		in, out := &in.TolerancePercent, &out.TolerancePercent
		*out = new(uint)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscreteValueOutOfList.
func (in *DiscreteValueOutOfList) DeepCopy() *DiscreteValueOutOfList {
	if in == nil {
		return nil
	}
	out := new(DiscreteValueOutOfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulset) DeepCopyInto(out *KanaryStatefulset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulset.
func (in *KanaryStatefulset) DeepCopy() *KanaryStatefulset {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KanaryStatefulset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulsetCondition) DeepCopyInto(out *KanaryStatefulsetCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulsetCondition.
func (in *KanaryStatefulsetCondition) DeepCopy() *KanaryStatefulsetCondition {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulsetCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulsetList) DeepCopyInto(out *KanaryStatefulsetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KanaryStatefulset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulsetList.
func (in *KanaryStatefulsetList) DeepCopy() *KanaryStatefulsetList {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulsetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KanaryStatefulsetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulsetSpec) DeepCopyInto(out *KanaryStatefulsetSpec) {
	*out = *in
	// in.Template.DeepCopyInto(&out.Template)
	in.Validations.DeepCopyInto(&out.Validations)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulsetSpec.
func (in *KanaryStatefulsetSpec) DeepCopy() *KanaryStatefulsetSpec {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulsetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulsetSpecValidation) DeepCopyInto(out *KanaryStatefulsetSpecValidation) {
	*out = *in
	if in.Manual != nil {
		in, out := &in.Manual, &out.Manual
		*out = new(KanaryStatefulsetSpecValidationManual)
		**out = **in
	}
	if in.LabelWatch != nil {
		in, out := &in.LabelWatch, &out.LabelWatch
		*out = new(KanaryStatefulsetSpecValidationLabelWatch)
		(*in).DeepCopyInto(*out)
	}
	if in.PromQL != nil {
		in, out := &in.PromQL, &out.PromQL
		*out = new(KanaryStatefulsetSpecValidationPromQL)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulsetSpecValidation.
func (in *KanaryStatefulsetSpecValidation) DeepCopy() *KanaryStatefulsetSpecValidation {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulsetSpecValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulsetSpecValidationLabelWatch) DeepCopyInto(out *KanaryStatefulsetSpecValidationLabelWatch) {
	*out = *in
	if in.PodInvalidationLabels != nil {
		in, out := &in.PodInvalidationLabels, &out.PodInvalidationLabels
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentInvalidationLabels != nil {
		in, out := &in.DeploymentInvalidationLabels, &out.DeploymentInvalidationLabels
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulsetSpecValidationLabelWatch.
func (in *KanaryStatefulsetSpecValidationLabelWatch) DeepCopy() *KanaryStatefulsetSpecValidationLabelWatch {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulsetSpecValidationLabelWatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulsetSpecValidationList) DeepCopyInto(out *KanaryStatefulsetSpecValidationList) {
	*out = *in
	if in.InitialDelay != nil {
		in, out := &in.InitialDelay, &out.InitialDelay
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ValidationPeriod != nil {
		in, out := &in.ValidationPeriod, &out.ValidationPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxIntervalPeriod != nil {
		in, out := &in.MaxIntervalPeriod, &out.MaxIntervalPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KanaryStatefulsetSpecValidation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulsetSpecValidationList.
func (in *KanaryStatefulsetSpecValidationList) DeepCopy() *KanaryStatefulsetSpecValidationList {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulsetSpecValidationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulsetSpecValidationManual) DeepCopyInto(out *KanaryStatefulsetSpecValidationManual) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulsetSpecValidationManual.
func (in *KanaryStatefulsetSpecValidationManual) DeepCopy() *KanaryStatefulsetSpecValidationManual {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulsetSpecValidationManual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulsetSpecValidationPromQL) DeepCopyInto(out *KanaryStatefulsetSpecValidationPromQL) {
	*out = *in
	if in.ValueInRange != nil {
		in, out := &in.ValueInRange, &out.ValueInRange
		*out = new(ValueInRange)
		(*in).DeepCopyInto(*out)
	}
	if in.DiscreteValueOutOfList != nil {
		in, out := &in.DiscreteValueOutOfList, &out.DiscreteValueOutOfList
		*out = new(DiscreteValueOutOfList)
		(*in).DeepCopyInto(*out)
	}
	if in.ContinuousValueDeviation != nil {
		in, out := &in.ContinuousValueDeviation, &out.ContinuousValueDeviation
		*out = new(ContinuousValueDeviation)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulsetSpecValidationPromQL.
func (in *KanaryStatefulsetSpecValidationPromQL) DeepCopy() *KanaryStatefulsetSpecValidationPromQL {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulsetSpecValidationPromQL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulsetStatus) DeepCopyInto(out *KanaryStatefulsetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]KanaryStatefulsetCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Report = in.Report
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulsetStatus.
func (in *KanaryStatefulsetStatus) DeepCopy() *KanaryStatefulsetStatus {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulsetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryStatefulsetStatusReport) DeepCopyInto(out *KanaryStatefulsetStatusReport) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryStatefulsetStatusReport.
func (in *KanaryStatefulsetStatusReport) DeepCopy() *KanaryStatefulsetStatusReport {
	if in == nil {
		return nil
	}
	out := new(KanaryStatefulsetStatusReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueInRange) DeepCopyInto(out *ValueInRange) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueInRange.
func (in *ValueInRange) DeepCopy() *ValueInRange {
	if in == nil {
		return nil
	}
	out := new(ValueInRange)
	in.DeepCopyInto(out)
	return out
}
